name: aur_sunao
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_auth: ^0.15.0+1
  double_back_to_close_app: ^0.1.2
  flutter_tts: ^0.7.0
  firebase_ml_vision: ^0.9.3+3
  image_picker_modern: ^0.4.12+2
  speech_recognition: ^0.3.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat-Medium.ttf
          weight: 600
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 500
        - asset: fonts/Montserrat-Thin.ttf
          weight: 300
    - family: SourceSansPro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
        - asset: fonts/SourceSansPro-Bold.ttf
          weight: 700
        - asset: fonts/SourceSansPro-Light.ttf
          weight: 400
        - asset: fonts/SourceSansPro-SemiBold.ttf
          weight: 500